spring:
  datasource:
    platform: h2
    url: jdbc:h2:file:~/db/german-test;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: user
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true