spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    platform: postgres
    driver-class-name: org.postgresql.Driver
    schema: germantv
    jpa:
    show-sql: true
    packages-to-scan: com.spring.german
    hibernate:
      ddl-auto: update
logging:
  level: debug