spring:
  profiles:
    active: test
server:
  port: 8080

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:file:~/db/collaboratory;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: root
    password: root

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/collaboratory
    username: root
    password: root
    initialize: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update